// export type DummyData = {
//     "id": string,
//     "symbol": string,
//     "name": string,
//     "image": string,
//     "current_price": number,
//     "market_cap": number,
//     "market_cap_rank": number,
//     "fully_diluted_valuation": number | null,
//     "total_volume": number,
//     "high_24h": number,
//     "low_24h": number,
//     "price_change_24h": number,
//     "price_change_percentage_24h": number,
//     "market_cap_change_24h": number,
//     "market_cap_change_percentage_24h": number,
//     "circulating_supply": number,
//     "total_supply": number | null,
//     "max_supply": number | null,
//     "ath": number,
//     "ath_change_percentage": number,
//     "ath_date": string,
//     "atl": number,
//     "atl_change_percentage": number,
//     "atl_date": string,
//     "roi": null,
//     "last_updated": string
// }

export type CoinListCoin = {
    "id": string,
    "symbol": string,
    "name": string,
    "image": string,
    "current_price": number,
    "market_cap": number,
    "market_cap_rank": number,
    "fully_diluted_valuation": number | null,
    "total_volume": number,
    "high_24h": number,
    "low_24h": number,
    "price_change_24h": number,
    "price_change_percentage_24h": number,
    "market_cap_change_24h": number,
    "market_cap_change_percentage_24h": number,
    "circulating_supply": number,
    "total_supply": number | null,
    "max_supply": number | null,
    "ath": number,
    "ath_change_percentage": number,
    "ath_date": string,
    "atl": number,
    "atl_change_percentage": number,
    "atl_date": string,
    "roi": null,
    "last_updated": string
}

export type cryptoItemHeld = {
    name: String,
    img: String,
    purchase_price: Number,
    current_price: Number,
    volume: Number,
    total_value: Number,
    percentage_change: Number,
    price_change: Number,
    date: String,
};

export type cryptoHistoryItem = {
    name: String,
    img: String,
    buy_sell: Boolean,
    purchase_price: Number,
    sell_price: Number,
    volume: Number,
    date: String,
}